apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ocp4-dwatch
  namespace: ocp4-dwatch
  labels:
    app: ocp4-dwatch
spec:
  selector:
    matchLabels:
      name: ocp4-dwatch
  template:
    metadata:
      labels:
        name: ocp4-dwatch
    spec:
      containers:
      - name: ocp4-dwatch
        image: quay.io/robbmanes/ocp4-dwatch:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        volumeMounts:
        - mountPath: /hostproc
          name: proc
        - mountPath: /dev/kmsg
          name: dev
        terminationGracePeriodSeconds: 30
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: dev
        hostPath:
          path: /dev/kmsg
          type: CharDevice
      serviceAccount: ocp4-dwatch
      serviceAccountName: ocp4-dwatch
      securityContext:
        runAsUser: 0
