apiVersion: v1
kind: PersistentVolumeClaim
namespace: kube-system
metadata:
  name: rhcos-dwatch-proc-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
